# Copyright (C) [2024] [Christian Marinkovich]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
    File: TextureSetup.py
    Author: Christian Marinkovich
    Date: 2024-08-01
    Description:
    This file is used to correctly load all of the textures into the game based off whether fullscreen mode is on
        or off.
"""

# Import the current fullscreen configuration
from setup.ConfigurationSetupPygame import settings
fullscreen = settings.fullscreen

# Determine whether to use scaled textures or not based on if fullscreen is on or off
MACHINE_PLAYER_TEXTURE = "textures/player/Player.png" if fullscreen == 0 else "textures/player/Player_Scaled.png"
MACHINE_WASHER_TEXTURE = "textures/player/Machine_Washer.png" if fullscreen == 0 else "textures/player/Machine_Washer_Scaled.png"
THE_INCINERATOR_TEXTURE = "textures/player/The_Incinerator.png" if fullscreen == 0 else "textures/player/The_Incinerator_Scaled.png"
THE_BLACK_HOLE_TEXTURE = "textures/player/The_Black_Hole.png" if fullscreen == 0 else "textures/player/The_Black_Hole_Scaled.png"
THE_STAR_KILLER_TEXTURE = "textures/player/The_Star_Killer.png" if fullscreen == 0 else "textures/player/The_Star_Killer_Scaled.png"
MACHINE_PLAYER_LASER_TEXTURE = "textures/lasers/Player_Laser.png" if fullscreen == 0 else "textures/lasers/Player_Laser_Scaled.png"
MACHINE_WASHER_LASER_TEXTURE = "textures/lasers/Machine_Washer_Laser.png" if fullscreen == 0 else "textures/lasers/Machine_Washer_Laser_Scaled.png"
INCINERATOR_LASER_TEXTURE = "textures/lasers/Incinerator_Laser.png" if fullscreen == 0 else "textures/lasers/Incinerator_Laser_Scaled.png"
BLACK_HOLE_LASER_TEXTURE = "textures/lasers/The_Black_Hole_Laser.png" if fullscreen == 0 else "textures/lasers/The_Black_Hole_Laser_Scaled.png"
STAR_KILLER_LASER_TEXTURE = "textures/lasers/The_Star_Killer_Laser.png" if fullscreen == 0 else "textures/lasers/The_Star_Killer_Laser_Scaled.png"
BLUE_MACHINE_TEXTURE = "textures/machines/Enemy(1-5).png" if fullscreen == 0 else "textures/machines/Enemy(1-5)_Scaled.png"
BLUE_MACHINE_LASER_TEXTURE = "textures/lasers/Enemy(1-5)_Laser.png" if fullscreen == 0 else "textures/lasers/Enemy(1-5)_Laser_Scaled.png"
YELLOW_MACHINE_TEXTURE = "textures/machines/Enemy(6-10).png" if fullscreen == 0 else "textures/machines/Enemy(6-10)_Scaled.png"
YELLOW_MACHINE_LASER_TEXTURE = "textures/lasers/Enemy(6-10)_Laser.png" if fullscreen == 0 else "textures/lasers/Enemy(6-10)_Laser_Scaled.png"
RED_MACHINE_TEXTURE = "textures/machines/Enemy(11-15).png" if fullscreen == 0 else "textures/machines/Enemy(11-15)_Scaled.png"
RED_MACHINE_LASER_TEXTURE = "textures/lasers/Enemy(11-15)_Laser.png" if fullscreen == 0 else "textures/lasers/Enemy(11-15)_Laser_Scaled.png"
MACHINE_BOSS_TEXTURE = "textures/machines/Boss.png" if fullscreen == 0 else "textures/machines/Boss_Scaled.png"
MACHINE_BOSS_LASER_TEXTURE = "textures/lasers/Boss_Laser.png" if fullscreen == 0 else "textures/lasers/Boss_Laser_Scaled.png"
HEALTH_BAR_22_TEXTURE = "textures/healthbars/HealthBar_2.2.png" if fullscreen == 0 else "textures/healthbars/HealthBar_2.2_Scaled.png"
HEALTH_BAR_12_TEXTURE = "textures/healthbars/HealthBar_2.1.png" if fullscreen == 0 else "textures/healthbars/HealthBar_2.1_Scaled.png"
HEALTH_BAR_1010_TEXTURE = "textures/healthbars/HealthBar_10.10.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.10_Scaled.png"
HEALTH_BAR_910_TEXTURE = "textures/healthbars/HealthBar_10.9.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.9_Scaled.png"
HEALTH_BAR_810_TEXTURE = "textures/healthbars/HealthBar_10.8.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.8_Scaled.png"
HEALTH_BAR_710_TEXTURE = "textures/healthbars/HealthBar_10.7.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.7_Scaled.png"
HEALTH_BAR_610_TEXTURE = "textures/healthbars/HealthBar_10.6.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.6_Scaled.png"
HEALTH_BAR_510_TEXTURE = "textures/healthbars/HealthBar_10.5.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.5_Scaled.png"
HEALTH_BAR_410_TEXTURE = "textures/healthbars/HealthBar_10.4.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.4_Scaled.png"
HEALTH_BAR_310_TEXTURE = "textures/healthbars/HealthBar_10.3.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.3_Scaled.png"
HEALTH_BAR_210_TEXTURE = "textures/healthbars/HealthBar_10.2.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.2_Scaled.png"
HEALTH_BAR_110_TEXTURE = "textures/healthbars/HealthBar_10.1.png" if fullscreen == 0 else "textures/healthbars/HealthBar_10.1_Scaled.png"
HEALTH_BAR_33_TEXTURE = "textures/healthbars/HealthBar_3.3.png" if fullscreen == 0 else "textures/healthbars/HealthBar_3.3_Scaled.png"
HEALTH_BAR_23_TEXTURE = "textures/healthbars/HealthBar_3.2.png" if fullscreen == 0 else "textures/healthbars/HealthBar_3.2_Scaled.png"
HEALTH_BAR_13_TEXTURE = "textures/healthbars/HealthBar_3.1.png" if fullscreen == 0 else "textures/healthbars/HealthBar_3.1_Scaled.png"
ARMOR_BAR_10_10_TEXTURE = "textures/armor/ArmorBar_10.10.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.10_Scaled.png"
ARMOR_BAR_10_9_TEXTURE = "textures/armor/ArmorBar_10.9.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.9_Scaled.png"
ARMOR_BAR_10_8_TEXTURE = "textures/armor/ArmorBar_10.8.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.8_Scaled.png"
ARMOR_BAR_10_7_TEXTURE = "textures/armor/ArmorBar_10.7.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.7_Scaled.png"
ARMOR_BAR_10_6_TEXTURE = "textures/armor/ArmorBar_10.6.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.6_Scaled.png"
ARMOR_BAR_10_5_TEXTURE = "textures/armor/ArmorBar_10.5.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.5_Scaled.png"
ARMOR_BAR_10_4_TEXTURE = "textures/armor/ArmorBar_10.4.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.4_Scaled.png"
ARMOR_BAR_10_3_TEXTURE = "textures/armor/ArmorBar_10.3.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.3_Scaled.png"
ARMOR_BAR_10_2_TEXTURE = "textures/armor/ArmorBar_10.2.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.2_Scaled.png"
ARMOR_BAR_10_1_TEXTURE = "textures/armor/ArmorBar_10.1.png" if fullscreen == 0 else "textures/armor/ArmorBar_10.1_Scaled.png"
EXPLOSION_1_TEXTURE = "textures/explosions/Explosion1.png" if fullscreen == 0 else "textures/explosions/Explosion1_Scaled.png"
EXPLOSION_2_TEXTURE = "textures/explosions/Explosion2.png" if fullscreen == 0 else "textures/explosions/Explosion2_Scaled.png"
GROUND_TEXTURE = "textures/ground/Ground.png" if fullscreen == 0 else "textures/ground/Ground_Scaled.png"
SUN_TEXTURE = "textures/background/Sun.png" if fullscreen == 0 else "textures/background/Sun_Scaled.png"
EARTH_TEXTURE = "textures/background/Earth.png" if fullscreen == 0 else "textures/background/Earth_Scaled.png"
SPACE_SHIP_TEXTURE = "textures/background/Space_Ship.png" if fullscreen == 0 else "textures/background/Space_Ship_Scaled.png"
HUMAN_STILL_RIGHT_TEXTURE = "textures/player/Player_Head_Still_Right.png" if fullscreen == 0 else "textures/player/Player_Head_Still_Right_Scaled.png"
HUMAN_STILL_LEFT_TEXTURE = "textures/player/Player_Head_Still_Left.png" if fullscreen == 0 else "textures/player/Player_Head_Still_Left_Scaled.png"
HUMAN_WALKING_RIGHT_TEXTURE = "textures/player/Player_Head_Walking_Right.png" if fullscreen == 0 else "textures/player/Player_Head_Walking_Right_Scaled.png"
HUMAN_WALKING_LEFT_TEXTURE = "textures/player/Player_Head_Walking_Left.png" if fullscreen == 0 else "textures/player/Player_Head_Walking_Left_Scaled.png"
PLAYER_HEAD_LASER_TEXTURE = "textures/lasers/Player_Head_Laser.png" if fullscreen == 0 else "textures/lasers/Player_Head_Laser_Scaled.png"
THE_COOKER_LASER_TEXTURE = "textures/lasers/The_Cooker_Laser.png" if fullscreen == 0 else "textures/lasers/The_Cooker_Laser_Scaled.png"
POISON_DART_LASER_TEXTURE = "textures/lasers/Poison_Dart_Laser.png" if fullscreen == 0 else "textures/lasers/Poison_Dart_Laser_Scaled.png"
METEOR_GUN_LASER_RIGHT_TEXTURE = "textures/lasers/Meteor_Gun_Laser_Right.png" if fullscreen == 0 else "textures/lasers/Meteor_Gun_Laser_Right_Scaled.png"
METEOR_GUN_LASER_LEFT_TEXTURE = "textures/lasers/Meteor_Gun_Laser_Left.png" if fullscreen == 0 else "textures/lasers/Meteor_Gun_Laser_Left_Scaled.png"
SUPERNOVA_LASER_RIGHT_TEXTURE = "textures/lasers/The_Supernova_Laser_Right.png" if fullscreen == 0 else "textures/lasers/The_Supernova_Laser_Right_Scaled.png"
SUPERNOVA_LASER_LEFT_TEXTURE = "textures/lasers/The_Supernova_Laser_Left.png" if fullscreen == 0 else "textures/lasers/The_Supernova_Laser_Left_Scaled.png"
PLAYER_GUN_RIGHT_TEXTURE = "textures/gun/Player_Gun_Right.png" if fullscreen == 0 else "textures/gun/Player_Gun_Right_Scaled.png"
PLAYER_GUN_LEFT_TEXTURE = "textures/gun/Player_Gun_Left.png" if fullscreen == 0 else "textures/gun/Player_Gun_Left_Scaled.png"
THE_COOKER_RIGHT_TEXTURE = "textures/gun/The_Cooker_Right.png" if fullscreen == 0 else "textures/gun/The_Cooker_Right_Scaled.png"
THE_COOKER_LEFT_TEXTURE = "textures/gun/The_Cooker_Left.png" if fullscreen == 0 else "textures/gun/The_Cooker_Left_Scaled.png"
POISON_DART_GUN_RIGHT_TEXTURE = "textures/gun/Poison_Dart_Gun_Right.png" if fullscreen == 0 else "textures/gun/Poison_Dart_Gun_Right_Scaled.png"
POISON_DART_GUN_LEFT_TEXTURE = "textures/gun/Poison_Dart_Gun_Left.png" if fullscreen == 0 else "textures/gun/Poison_Dart_Gun_Left_Scaled.png"
METEOR_GUN_RIGHT_TEXTURE = "textures/gun/Meteor_Gun_Right.png" if fullscreen == 0 else "textures/gun/Meteor_Gun_Right_Scaled.png"
METEOR_GUN_LEFT_TEXTURE = "textures/gun/Meteor_Gun_Left.png" if fullscreen == 0 else "textures/gun/Meteor_Gun_Left_Scaled.png"
SUPERNOVA_RIGHT_TEXTURE = "textures/gun/Supernova_Right.png" if fullscreen == 0 else "textures/gun/Supernova_Right_Scaled.png"
SUPERNOVA_LEFT_TEXTURE = "textures/gun/Supernova_Left.png" if fullscreen == 0 else "textures/gun/Supernova_Left_Scaled.png"
OXYGEN_TANK_TEXTURE = "textures/other/Oxygen_Tank.png" if fullscreen == 0 else "textures/other/Oxygen_Tank_Scaled.png"
ALIEN_STILL_LEFT_1_5_TEXTURE = "textures/aliens/Alien_Still_Left(1-5).png" if fullscreen == 0 else "textures/aliens/Alien_Still_Left(1-5)_Scaled.png"
ALIEN_STILL_RIGHT_1_5_TEXTURE = "textures/aliens/Alien_Still_Right(1-5).png" if fullscreen == 0 else "textures/aliens/Alien_Still_Right(1-5)_Scaled.png"
ALIEN_WALKING_LEFT_1_5_TEXTURE = "textures/aliens/Alien_Walking_Left(1-5).png" if fullscreen == 0 else "textures/aliens/Alien_Walking_Left(1-5)_Scaled.png"
ALIEN_WALKING_RIGHT_1_5_TEXTURE = "textures/aliens/Alien_Walking_Right(1-5).png" if fullscreen == 0 else "textures/aliens/Alien_Walking_Right(1-5)_Scaled.png"
ALIEN_STILL_LEFT_6_10_TEXTURE = "textures/aliens/Alien_Still_Left(6-10).png" if fullscreen == 0 else "textures/aliens/Alien_Still_Left(6-10)_Scaled.png"
ALIEN_STILL_RIGHT_6_10_TEXTURE = "textures/aliens/Alien_Still_Right(6-10).png" if fullscreen == 0 else "textures/aliens/Alien_Still_Right(6-10)_Scaled.png"
ALIEN_WALKING_LEFT_6_10_TEXTURE = "textures/aliens/Alien_Walking_Left(6-10).png" if fullscreen == 0 else "textures/aliens/Alien_Walking_Left(6-10)_Scaled.png"
ALIEN_WALKING_RIGHT_6_10_TEXTURE = "textures/aliens/Alien_Walking_Right(6-10).png" if fullscreen == 0 else "textures/aliens/Alien_Walking_Right(6-10)_Scaled.png"
ALIEN_STILL_LEFT_11_15_TEXTURE = "textures/aliens/Alien_Still_Left(11-15).png" if fullscreen == 0 else "textures/aliens/Alien_Still_Left(11-15)_Scaled.png"
ALIEN_STILL_RIGHT_11_15_TEXTURE = "textures/aliens/Alien_Still_Right(11-15).png" if fullscreen == 0 else "textures/aliens/Alien_Still_Right(11-15)_Scaled.png"
ALIEN_WALKING_LEFT_11_15_TEXTURE = "textures/aliens/Alien_Walking_Left(11-15).png" if fullscreen == 0 else "textures/aliens/Alien_Walking_Left(11-15)_Scaled.png"
ALIEN_WALKING_RIGHT_11_15_TEXTURE = "textures/aliens/Alien_Walking_Right(11-15).png" if fullscreen == 0 else "textures/aliens/Alien_Walking_Right(11-15)_Scaled.png"
ALIEN_BOSS_TEXTURE = "textures/aliens/Alien_Boss.png" if fullscreen == 0 else "textures/aliens/Alien_Boss_Scaled.png"
ALIEN_DEATH_1_TEXTURE = "textures/explosions/Alien_Death_1.png" if fullscreen == 0 else "textures/explosions/Alien_Death_1_Scaled.png"
ALIEN_DEATH_2_TEXTURE = "textures/explosions/Alien_Death_2.png" if fullscreen == 0 else "textures/explosions/Alien_Death_2_Scaled.png"
PLAYER_DEATH_1_TEXTURE = "textures/explosions/Player_Death_1.png" if fullscreen == 0 else "textures/explosions/Player_Death_1_Scaled.png"
PLAYER_DEATH_2_TEXTURE = "textures/explosions/Player_Death_2.png" if fullscreen == 0 else "textures/explosions/Player_Death_2_Scaled.png"
SOUND_BUTTON_TEXTURE = "textures/buttons/Sound_Button.png" if fullscreen == 0 else "textures/buttons/Sound_Button_Scaled.png"
CONTROL_BUTTON_TEXTURE = "textures/buttons/Control_Button.png" if fullscreen == 0 else "textures/buttons/Control_Button_Scaled.png"
SETTINGS_MAIN_MENU_BUTTON_TEXTURE = "textures/buttons/Settings_Main_Menu_Button.png" if fullscreen == 0 else "textures/buttons/Settings_Main_Menu_Button_Scaled.png"
MAIN_MENU_BUTTON_MAIN_TEXTURE = "textures/buttons/Main_Menu_Button_Main.png" if fullscreen == 0 else "textures/buttons/Main_Menu_Button_Main_Scaled.png"
TITLE_SCREEN_BUTTON_TEXTURE = "textures/buttons/Title_Screen_Button.png" if fullscreen == 0 else "textures/buttons/Title_Screen_Button_Scaled.png"
TITLE_SCREEN_BUTTON_SMALL_TEXTURE = "textures/buttons/Title_Screen_Button_Small.png" if fullscreen == 0 else "textures/buttons/Title_Screen_Button_Small_Scaled.png"
MAIN_MENU_BUTTON_MAIN_HIGHLIGHTED_TEXTURE = "textures/buttons/Main_Menu_Button_Main_Highlighted.png" if fullscreen == 0 else "textures/buttons/Main_Menu_Button_Main_Highlighted_Scaled.png"
TITLE_SCREEN_BUTTON_HIGHLIGHTED_TEXTURE = "textures/buttons/Title_Screen_Button_Highlighted.png" if fullscreen == 0 else "textures/buttons/Title_Screen_Button_Highlighted_Scaled.png"
TITLE_SCREEN_BUTTON_SMALL_HIGHLIGHTED_TEXTURE = "textures/buttons/Title_Screen_Button_Small_Highlighted.png" if fullscreen == 0 else "textures/buttons/Title_Screen_Button_Small_Highlighted_Scaled.png"
BUY_BUTTON_TEXTURE = "textures/buttons/Buy_Button.png" if fullscreen == 0 else "textures/buttons/Buy_Button_Scaled.png"
BUY_BUTTON_HIGHLIGHTED_TEXTURE = "textures/buttons/Buy_Button_Highlighted.png" if fullscreen == 0 else "textures/buttons/Buy_Button_Highlighted_Scaled.png"
INVENTORY_SLOT_FRAME_TEXTURE = "textures/buttons/Inventory_Slot_Frame.png" if fullscreen == 0 else "textures/buttons/Inventory_Slot_Frame_Scaled.png"
INVENTORY_SLOT_FRAME_HIGHLIGHTED_TEXTURE = "textures/buttons/Inventory_Slot_Frame_Highlighted.png" if fullscreen == 0 else "textures/buttons/Inventory_Slot_Frame_Highlighted_Scaled.png"
TAB_TEXTURE = "textures/buttons/Tab.png" if fullscreen == 0 else "textures/buttons/Tab_Scaled.png"
TAB_HIGHLIGHTED_TEXTURE = "textures/buttons/Tab_Highlighted.png" if fullscreen == 0 else "textures/buttons/Tab_Highlighted_Scaled.png"
SIDE_PANEL_SHOP_TEXTURE = "textures/gui/Side_Panel_Shop.png" if fullscreen == 0 else "textures/gui/Side_Panel_Shop_Scaled.png"
POP_UP_MESSAGE_FRAME_TEXTURE = "textures/gui/Pop_Up_Message_Frame.png" if fullscreen == 0 else "textures/gui/Pop_Up_Message_Frame_Scaled.png"
LOCKED_TEXTURE = "textures/gui/Locked.png" if fullscreen == 0 else "textures/gui/Locked_Scaled.png"
TAB_SELECTOR_TEXTURE = "textures/gui/Tab_Selector.png" if fullscreen == 0 else "textures/gui/Tab_Selector_Scaled.png"
SLOT_SELECTOR_TEXTURE = "textures/gui/Slot_Selector.png" if fullscreen == 0 else "textures/gui/Slot_Selector_Scaled.png"
SETTINGS_AND_CONTROLS_BUTTON_TEXTURE = "textures/buttons/Settings_And_Controls_Button.png" if fullscreen == 0 else "textures/buttons/Settings_And_Controls_Button_Scaled.png"
SETTINGS_AND_CONTROLS_BUTTON_HIGHLIGHTED_TEXTURE = "textures/buttons/Settings_And_Controls_Button_Highlighted.png" if fullscreen == 0 else "textures/buttons/Settings_And_Controls_Button_Highlighted_Scaled.png"
MACHINE_DEFAULT_DISPLAY_ICON_TEXTURE = "textures/interface/display/Machine_Default_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Machine_Default_Display_Icon_Scaled.png"
MACHINE_WASHER_DISPLAY_ICON_TEXTURE = "textures/interface/display/Machine_Washer_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Machine_Washer_Display_Icon_Scaled.png"
THE_INCINERATOR_DISPLAY_ICON_TEXTURE = "textures/interface/display/The_Incinerator_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/The_Incinerator_Display_Icon_Scaled.png"
THE_BLACK_HOLE_DISPLAY_ICON_TEXTURE = "textures/interface/display/The_Black_Hole_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/The_Black_Hole_Display_Icon_Scaled.png"
THE_STAR_KILLER_DISPLAY_ICON_TEXTURE = "textures/interface/display/The_Star_Killer_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/The_Star_Killer_Display_Icon_Scaled.png"
ALIEN_DEFAULT_DISPLAY_ICON_TEXTURE = "textures/interface/display/Alien_Default_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Alien_Default_Display_Icon_Scaled.png"
THE_COOKER_DISPLAY_ICON_TEXTURE = "textures/interface/display/The_Cooker_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/The_Cooker_Display_Icon_Scaled.png"
POISON_DART_DISPLAY_ICON_TEXTURE = "textures/interface/display/Poison_Dart_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Poison_Dart_Display_Icon_Scaled.png"
METEOR_GUN_DISPLAY_ICON_TEXTURE = "textures/interface/display/Meteor_Gun_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Meteor_Gun_Display_Icon_Scaled.png"
SUPERNOVA_DISPLAY_ICON_TEXTURE = "textures/interface/display/Supernova_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Supernova_Display_Icon_Scaled.png"
YELLOW_POWER_UP_DISPLAY_ICON_TEXTURE = "textures/interface/display/Yellow_Power_Up_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Yellow_Power_Up_Display_Icon_Scaled.png"
BLUE_POWER_UP_DISPLAY_ICON_TEXTURE = "textures/interface/display/Blue_Power_Up_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Blue_Power_Up_Display_Icon_Scaled.png"
GREEN_POWER_UP_DISPLAY_ICON_TEXTURE = "textures/interface/display/Green_Power_Up_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Green_Power_Up_Display_Icon_Scaled.png"
RED_POWER_UP_DISPLAY_ICON_TEXTURE = "textures/interface/display/Red_Power_Up_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Red_Power_Up_Display_Icon_Scaled.png"
COIN_MAGNET_DISPLAY_ICON_TEXTURE = "textures/interface/display/Coin_Magnet_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Coin_Magnet_Display_Icon_Scaled.png"
ARMOR_DISPLAY_ICON_TEXTURE = "textures/interface/display/Armor_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Armor_Display_Icon_Scaled.png"
THORNS_DISPLAY_ICON_TEXTURE = "textures/interface/display/Thorns_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Thorns_Display_Icon_Scaled.png"
HEART_POWER_UP_DISPLAY_ICON_TEXTURE = "textures/interface/display/Heart_Power_Up_Display_Icon.png" if fullscreen == 0 else "textures/interface/display/Heart_Power_Up_Display_Icon_Scaled.png"
MACHINE_MODE_TAB_ICON_TEXTURE = "textures/interface/icons/tab/Machine_Mode_Tab_Icon.png" if fullscreen == 0 else "textures/interface/icons/tab/Machine_Mode_Tab_Icon_Scaled.png"
GADGETS_TAB_ICON_TEXTURE = "textures/interface/icons/tab/Gadgets_Tab_Icon.png" if fullscreen == 0 else "textures/interface/icons/tab/Gadgets_Tab_Icon_Scaled.png"
MACHINE_DEFAULT_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Machine_Default_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Machine_Default_Slot_Icon_Scaled.png"
MACHINE_WASHER_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Machine_Washer_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Machine_Washer_Slot_Icon_Scaled.png"
THE_INCINERATOR_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/The_Incinerator_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/The_Incinerator_Slot_Icon_Scaled.png"
THE_BLACK_HOLE_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/The_Black_Hole_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/The_Black_Hole_Slot_Icon_Scaled.png"
THE_STAR_KILLER_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/The_Star_Killer_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/The_Star_Killer_Slot_Icon_Scaled.png"
ALIEN_DEFAULT_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Alien_Default_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Alien_Default_Slot_Icon_Scaled.png"
THE_COOKER_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/The_Cooker_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/The_Cooker_Slot_Icon_Scaled.png"
POISON_DART_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Poison_Dart_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Poison_Dart_Slot_Icon_Scaled.png"
METEOR_GUN_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Meteor_Gun_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Meteor_Gun_Slot_Icon_Scaled.png"
SUPERNOVA_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Supernova_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Supernova_Slot_Icon_Scaled.png"
YELLOW_POWER_UP_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Yellow_Power_Up_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Yellow_Power_Up_Slot_Icon_Scaled.png"
RED_POWER_UP_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Red_Power_Up_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Red_Power_Up_Slot_Icon_Scaled.png"
GREEN_POWER_UP_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Green_Power_Up_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Green_Power_Up_Slot_Icon_Scaled.png"
BLUE_POWER_UP_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Blue_Power_Up_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Blue_Power_Up_Slot_Icon_Scaled.png"
COIN_MAGNET_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Coin_Magnet_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Coin_Magnet_Slot_Icon_Scaled.png"
ARMOR_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Armor_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Armor_Slot_Icon_Scaled.png"
THORNS_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Thorns_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Thorns_Slot_Icon_Scaled.png"
HEART_POWER_UP_SLOT_ICON_TEXTURE = "textures/interface/icons/slot/Heart_Power_Up_Slot_Icon.png" if fullscreen == 0 else "textures/interface/icons/slot/Heart_Power_Up_Slot_Icon_Scaled.png"
YELLOW_LIGHTNING_POWER_UP_TEXTURE = "textures/powerups/Yellow_Lightning_Power_Up.png" if fullscreen == 0 else "textures/powerups/Yellow_Lightning_Power_Up_Scaled.png"
GREEN_LIGHTNING_POWER_UP_TEXTURE = "textures/powerups/Green_Lightning_Power_Up.png" if fullscreen == 0 else "textures/powerups/Green_Lightning_Power_Up_Scaled.png"
RED_LIGHTNING_POWER_UP_TEXTURE = "textures/powerups/Red_Lightning_Power_Up.png" if fullscreen == 0 else "textures/powerups/Red_Lightning_Power_Up_Scaled.png"
BLUE_LIGHTNING_POWER_UP_TEXTURE = "textures/powerups/Blue_Lightning_Power_Up.png" if fullscreen == 0 else "textures/powerups/Blue_Lightning_Power_Up_Scaled.png"
HEART_POWER_UP_TEXTURE = "textures/powerups/Heart_Power_Up.png" if fullscreen == 0 else "textures/powerups/Heart_Power_Up_Scaled.png"
BLUE_POWER_UP_INDICATOR_ON_TEXTURE = "textures/powerups/Blue_Power_Up_Indicator_On.png" if fullscreen == 0 else "textures/powerups/Blue_Power_Up_Indicator_On_Scaled.png"
GREEN_POWER_UP_INDICATOR_ON_TEXTURE = "textures/powerups/Green_Power_Up_Indicator_On.png" if fullscreen == 0 else "textures/powerups/Green_Power_Up_Indicator_On_Scaled.png"
YELLOW_POWER_UP_INDICATOR_ON_TEXTURE = "textures/powerups/Yellow_Power_Up_Indicator_On.png" if fullscreen == 0 else "textures/powerups/Yellow_Power_Up_Indicator_On_Scaled.png"
RED_POWER_UP_INDICATOR_ON_TEXTURE = "textures/powerups/Red_Power_Up_Indicator_On.png" if fullscreen == 0 else "textures/powerups/Red_Power_Up_Indicator_On_Scaled.png"
BLUE_POWER_UP_INDICATOR_OFF_TEXTURE = "textures/powerups/Blue_Power_Up_Indicator_Off.png" if fullscreen == 0 else "textures/powerups/Blue_Power_Up_Indicator_Off_Scaled.png"
GREEN_POWER_UP_INDICATOR_OFF_TEXTURE = "textures/powerups/Green_Power_Up_Indicator_Off.png" if fullscreen == 0 else "textures/powerups/Green_Power_Up_Indicator_Off_Scaled.png"
YELLOW_POWER_UP_INDICATOR_OFF_TEXTURE = "textures/powerups/Yellow_Power_Up_Indicator_Off.png" if fullscreen == 0 else "textures/powerups/Yellow_Power_Up_Indicator_Off_Scaled.png"
RED_POWER_UP_INDICATOR_OFF_TEXTURE = "textures/powerups/Red_Power_Up_Indicator_Off.png" if fullscreen == 0 else "textures/powerups/Red_Power_Up_Indicator_Off_Scaled.png"
COPPER_COIN_TEXTURE = "textures/coins/Copper_Coin.png" if fullscreen == 0 else "textures/coins/Copper_Coin_Scaled.png"
SILVER_COIN_TEXTURE = "textures/coins/Silver_Coin.png" if fullscreen == 0 else "textures/coins/Silver_Coin_Scaled.png"
GOLD_COIN_TEXTURE = "textures/coins/Gold_Coin.png" if fullscreen == 0 else "textures/coins/Gold_Coin_Scaled.png"
PLATINUM_COIN_TEXTURE = "textures/coins/Platinum_Coin.png" if fullscreen == 0 else "textures/coins/Platinum_Coin_Scaled.png"
COIN_INDICATOR_TEXTURE = "textures/coins/Coin_Indicator.png" if fullscreen == 0 else "textures/coins/Coin_Indicator_Scaled.png"
